[project]
name = "arxiv-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arxiv>=2.2.0",
    "ipykernel>=6.29.5",
    "streamlit>=1.46.1",
    "tqdm>=4.67.1",
]
